name: Checkout and deploy
on: push
jobs:
  checkout:
    name: 'Checkout'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
        with:
          ref: 'main'

  install_dependancy:
    name: 'Install dependancy'
    needs: [checkout]
    runs-on: self-hosted
    steps:
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - run: npm cache verify
      - run: npm ci

  checkout_config:
    name: 'Checkout config'
    needs: [checkout]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
        with:
          ref: 'main'
          repository: wnynya/Wanyne-API-config
          token: ${{ secrets.CONFIG_TOKEN }}
          path: './config'
          clean: false

  deploy:
    name: 'Deploy'
    needs: [checkout, checkout_config, install_dependancy]
    runs-on: self-hosted
    steps:
      - run: ./start.sh
